# Generated by Django 2.0.5 on 2018-06-18 13:38

from django.db import migrations, models
import django.utils.timezone
import redirect301.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url301',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', redirect301.utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', redirect301.utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('old_url', models.URLField()),
                ('new_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
