# Generated by Django 2.0.5 on 2018-06-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect301', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url301',
            options={'ordering': ('new_url', 'old_url')},
        ),
    ]
