# Generated by Django 2.0.5 on 2018-06-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect301', '0002_auto_20180618_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url301',
            options={'ordering': ('new_reference', 'old_reference')},
        ),
        migrations.RemoveField(
            model_name='url301',
            name='new_url',
        ),
        migrations.RemoveField(
            model_name='url301',
            name='old_url',
        ),
        migrations.AddField(
            model_name='url301',
            name='new_reference',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url301',
            name='old_reference',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
