# Generated by Django 2.0.5 on 2018-06-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect301', '0003_auto_20180618_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='url301',
            name='app_name',
            field=models.CharField(default='song', max_length=20),
            preserve_default=False,
        ),
    ]
