# Generated by Django 2.0.6 on 2018-07-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='alternative_name',
            new_name='alt_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text',
            field=models.CharField(max_length=600),
        ),
    ]
