# Generated by Django 2.0.6 on 2018-07-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drb', '0002_auto_20180708_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versealt',
            name='book',
        ),
        migrations.DeleteModel(
            name='VerseAlt',
        ),
    ]
