# Generated by Django 2.0.6 on 2018-07-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drb', '0003_auto_20180708_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='testament',
            field=models.CharField(max_length=20),
        ),
    ]
