# Generated by Django 2.0 on 2017-12-29 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import universal.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voicing', '__first__'),
        ('language', '__first__'),
        ('siteuser', '__first__'),
        ('author', '0001_initial'),
        ('season', '__first__'),
        ('masspart', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('compose_date', models.DateField(blank=True, null=True)),
                ('slug', universal.fields.AutoSlugField(blank=True, editable=False, set_once=True, set_using='title')),
                ('lyrics', models.TextField(blank=True)),
                ('first_line', models.CharField(blank=True, max_length=100)),
                ('scripture_ref', models.CharField(blank=True, max_length=25)),
                ('tempo', models.IntegerField(blank=True, null=True)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('divisions', models.IntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='author.Author')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Language')),
                ('likes', models.ManyToManyField(related_name='score_likes', to='siteuser.SiteUser')),
                ('mass_parts', models.ManyToManyField(to='masspart.MassPart')),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteuser.SiteUser')),
                ('seasons', models.ManyToManyField(to='season.Season')),
                ('voicing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicing.Voicing')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
