# Generated by Django 2.0.5 on 2018-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('', 'Select a season'), ('ordinary time', 'Ordinary Time'), ('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('easter', 'Easter'), ('pentecost', 'Pentecost'), ('any', 'Any'), ('na', 'NA')], max_length=15, unique=True),
        ),
    ]
