# Generated by Django 2.0.5 on 2018-06-18 13:35

from django.db import migrations
import universal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=universal.fields.AutoSlugField(blank=True, editable=False, max_length=255, set_once=False, set_using='title'),
        ),
    ]
