# Generated by Django 2.0.5 on 2018-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_type',
            field=models.CharField(choices=[('liturgical', 'liturgical'), ('secular', 'secular')], default='liturgical', max_length=30),
        ),
        migrations.AlterField(
            model_name='masspart',
            name='part',
            field=models.CharField(choices=[('', 'Select Mass part'), ('entrance', 'entrance'), ('kyrie', 'kyrie'), ('gloria', 'gloria'), ('acclamation', 'acclamation'), ('offertory', 'offertory'), ('communion', 'communion'), ('sanctus', 'sanctus'), ('agnus dei', 'agnus dei'), ('recesssion', 'recesssion'), ('carol', 'carol'), ('general', 'general'), ('na', 'na')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('', 'Select Season'), ('ordinary time', 'ordinary time'), ('advent', 'advent'), ('christmas', 'christmas'), ('lent', 'lent'), ('Easter', 'easter'), ('pentecost', 'pentecost'), ('na', 'na')], max_length=15, unique=True),
        ),
    ]
