# Generated by Django 2.0.1 on 2018-02-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mass_parts',
            field=models.ManyToManyField(blank=True, null=True, to='masspart.MassPart'),
        ),
        migrations.AlterField(
            model_name='song',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, to='season.Season'),
        ),
    ]
