# Generated by Django 2.0.1 on 2018-01-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(related_name='song_likes', to='siteuser.SiteUser'),
        ),
    ]
