# Generated by Django 2.0.1 on 2018-05-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
