# Generated by Django 2.0.1 on 2018-02-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-created', 'publish']},
        ),
        migrations.RemoveField(
            model_name='song',
            name='status',
        ),
        migrations.AddField(
            model_name='song',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
