# Generated by Django 2.0.1 on 2018-03-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_youtube_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_playlist_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
