# Generated by Django 2.0.1 on 2018-02-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180213_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-created', 'publish', 'tempo_text']},
        ),
        migrations.AddField(
            model_name='song',
            name='tempo_text',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
