# Generated by Django 2.0.1 on 2018-02-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180205_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-created', 'status']},
        ),
        migrations.AlterField(
            model_name='song',
            name='mass_parts',
            field=models.ManyToManyField(to='masspart.MassPart'),
        ),
        migrations.AlterField(
            model_name='song',
            name='seasons',
            field=models.ManyToManyField(to='season.Season'),
        ),
    ]
