# Generated by Django 2.0.5 on 2018-06-12 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180609_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='compose_date',
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.PositiveIntegerField(default=1000, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2018)]),
            preserve_default=False,
        ),
    ]
