# Generated by Django 2.0.5 on 2018-06-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180618_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masspart',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='song',
            name='ocassion',
            field=models.CharField(max_length=30),
        ),
    ]
