# Generated by Django 2.0.1 on 2018-03-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20180327_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
