# Generated by Django 2.0.5 on 2018-06-12 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20180613_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
