# Generated by Django 2.0.1 on 2018-02-28 07:01

from django.db import migrations
import universal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20180228_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title', '-created', 'publish', 'tempo_text']},
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=universal.fields.AutoSlugField(blank=True, editable=False, max_length=255, set_once=True, set_using='title'),
        ),
    ]
