# Generated by Django 2.0.5 on 2018-06-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20180602_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('', 'Select an option'), ('anthem', 'Anthem'), ('carol', 'Carol'), ('chorus', 'Chorus'), ('folk music', 'Folk music'), ('gregorian chant', 'Gregorian Chant'), ('hymn', 'Hymn'), ('mass', 'Mass'), ('motet', 'Motet'), ('popular music', 'Popular music'), ('psalm', 'Psalm'), ('requiem', 'Requiem'), ('sequence', 'Sequence')], default='hymn', max_length=30),
        ),
    ]
