# Generated by Django 2.0.5 on 2018-06-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20180613_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
    ]
