# Generated by Django 2.0.5 on 2018-06-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20180602_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masspart',
            name='part',
            field=models.CharField(choices=[('entrance', 'Entrance'), ('kyrie', 'Kyrie'), ('gloria', 'Gloria'), ('acclamation', 'Acclamation'), ('offertory', 'Offertory'), ('communion', 'Communion'), ('sanctus', 'Sanctus'), ('agnus dei', 'Agnus Dei'), ('recesssion', 'Recesssion'), ('na', 'NA')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('ordinary time', 'Ordinary Time'), ('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('Easter', 'Easter'), ('pentecost', 'Pentecost'), ('na', 'NA')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('', 'Select a genre'), ('anthem', 'Anthem'), ('carol', 'Carol'), ('chorus', 'Chorus'), ('folk music', 'Folk music'), ('gregorian chant', 'Gregorian Chant'), ('hymn', 'Hymn'), ('litany', 'Litany'), ('madrigral', 'Madrigal'), ('march', 'March'), ('mass', 'Mass'), ('motet', 'Motet'), ('popular music', 'Popular music'), ('psalm', 'Psalm'), ('requiem', 'Requiem'), ('sequence', 'Sequence'), ('na', 'NA')], default='hymn', max_length=30),
        ),
        migrations.AlterField(
            model_name='song',
            name='ocassion',
            field=models.CharField(choices=[('sacred', 'Sacred'), ('liturgical', 'Liturgical'), ('secular', 'Secular'), ('na', 'NA')], default='sacred', max_length=30),
        ),
    ]
