# Generated by Django 2.0.5 on 2018-06-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_remove_song_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='ocassion',
            field=models.CharField(choices=[('', 'Select ocassion'), ('sacred', 'Sacred'), ('liturgical', 'Liturgical'), ('secular', 'Secular'), ('na', 'NA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='song',
            name='originator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='siteuser.SiteUser'),
        ),
    ]
