# Generated by Django 2.0.5 on 2018-05-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20180526_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masspart',
            name='part',
            field=models.CharField(choices=[('entrance', 'Entrance'), ('kyrie', 'Kyrie'), ('gloria', 'Gloria'), ('acclamation', 'Acclamation'), ('offertory', 'Offertory'), ('communion', 'Communion'), ('sanctus', 'Sanctus'), ('agnus dei', 'Agnus Dei'), ('recesssion', 'Recesssion'), ('na', 'NA')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('ordinary time', 'Ordinary Time'), ('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('Easter', 'Easter'), ('pentecost', 'Pentecost'), ('na', 'NA')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_type',
            field=models.CharField(choices=[('liturgical', 'liturgical'), ('secular', 'secular'), ('na', 'na')], default='na', max_length=30),
        ),
    ]
