# Generated by Django 2.0.5 on 2018-05-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20180526_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('hymn', 'Hymn'), ('psalm', 'Psalm'), ('gregorian chant', 'Gregorian Chant'), ('sequence', 'Sequence'), ('chorus', 'Chorus'), ('carol', 'Carol'), ('requiem', 'Requiem'), ('mass', 'Mass'), ('anthem', 'Anthem'), ('popular music', 'Popular music'), ('folk music', 'Folk music')], default='hymn', max_length=30),
        ),
    ]
