# Generated by Django 2.0.1 on 2018-02-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_song_like_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('like_count', 'title', '-created', 'publish', 'tempo_text')},
        ),
    ]
