# Generated by Django 2.0.5 on 2018-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20180605_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masspart',
            name='part',
            field=models.CharField(choices=[('', 'Select a mass part'), ('entrance', 'Entrance'), ('kyrie', 'Kyrie'), ('gloria', 'Gloria'), ('acclamation', 'Acclamation'), ('offertory', 'Offertory'), ('communion', 'Communion'), ('sanctus', 'Sanctus'), ('agnus dei', 'Agnus Dei'), ('recesssion', 'Recesssion'), ('na', 'NA')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('', 'Select a season'), ('ordinary time', 'Ordinary Time'), ('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('Easter', 'Easter'), ('pentecost', 'Pentecost'), ('na', 'NA')], max_length=15, unique=True),
        ),
    ]
