# Generated by Django 2.0.5 on 2018-05-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_type',
            field=models.CharField(choices=[('sacred', 'Sacred/Liturgical'), ('secular', 'Secular'), ('na', 'na')], default='sacred', max_length=30),
        ),
    ]
