# Generated by Django 2.0.1 on 2018-02-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_auto_20180228_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('-like_count', 'title', '-created', 'publish', 'tempo_text')},
        ),
        migrations.RenameField(
            model_name='song',
            old_name='scripture_ref',
            new_name='scripture_reference',
        ),
    ]
