# Generated by Django 2.0.5 on 2018-05-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_auto_20180526_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='first_line',
        ),
    ]
