# Generated by Django 2.0.5 on 2018-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0011_auto_20180526_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masspart',
            name='part',
            field=models.CharField(choices=[('', 'Selecta an option'), ('entrance', 'Entrance'), ('kyrie', 'Kyrie'), ('gloria', 'Gloria'), ('acclamation', 'Acclamation'), ('offertory', 'Offertory'), ('communion', 'Communion'), ('sanctus', 'Sanctus'), ('agnus dei', 'Agnus Dei'), ('recesssion', 'Recesssion'), ('na', 'NA')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('', 'Selecta an option'), ('ordinary time', 'Ordinary Time'), ('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('Easter', 'Easter'), ('pentecost', 'Pentecost'), ('na', 'NA')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('', 'Selecta an option'), ('hymn', 'Hymn'), ('psalm', 'Psalm'), ('gregorian chant', 'Gregorian Chant'), ('sequence', 'Sequence'), ('chorus', 'Chorus'), ('carol', 'Carol'), ('requiem', 'Requiem'), ('mass', 'Mass'), ('anthem', 'Anthem'), ('popular music', 'Popular music'), ('folk music', 'Folk music')], default='hymn', max_length=30),
        ),
    ]
