# Generated by Django 2.0.5 on 2018-06-19 09:36

from django.db import migrations
import universal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=universal.fields.AutoSlugField(blank=True, editable=False, set_once=False, set_using='title'),
        ),
    ]
