# Generated by Django 2.0.1 on 2018-03-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180301_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-like_count', '-created')},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-like_count', '-created', 'title')},
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
