# Generated by Django 2.0.5 on 2018-06-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_type',
            field=models.CharField(choices=[('', 'Select author type'), ('lyricist', 'Lyricist'), ('composer', 'Composer')], default='lyricist', max_length=15),
        ),
    ]
