# Generated by Django 2.0.1 on 2018-03-09 13:27

from django.db import migrations
import universal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=universal.fields.AutoMultipleSlugField(blank=True, editable=False, max_length=255, set_once=True, set_using=['last_name', 'first_name']),
        ),
    ]
