# Generated by Django 2.0.5 on 2018-06-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20180613_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_type',
            field=models.CharField(choices=[('', 'Select author type'), ('lyricist', 'Lyricist'), ('composer', 'Composer'), ('lyricist and composer', 'Lyricist and Composer')], max_length=30),
        ),
    ]
