# Generated by Django 2.0.1 on 2018-01-21 14:08

from django.db import migrations, models
import django.utils.timezone
import universal.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('part', models.CharField(choices=[('', 'Select Mass part'), ('ENTRANCE', 'Entrance'), ('KYRIE', 'Kyrie'), ('GLORIA', 'Gloria'), ('ACCLAMATION', 'Acclamation'), ('OFFERTORY', 'Offertory'), ('COMMUNION', 'Communion'), ('SANCTUS', 'Sanctus'), ('AGNUS DEI', 'Agnus Dei'), ('RECESSION', 'Recesssion'), ('CAROL', 'Carol'), ('GENERAL', 'General'), ('NA', 'NA')], max_length=15, unique=True)),
                ('about', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
