# Generated by Django 2.0.1 on 2018-02-09 20:13

from django.db import migrations, models
import django.utils.timezone
import universal.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('season', models.CharField(choices=[('', 'Select Season'), ('ORDINARY TIME', 'Ordinary Time'), ('ADVENT', 'Advent'), ('CHRISTMAS', 'Christmas'), ('LENT', 'Lent'), ('EASTER', 'Easter'), ('PENTECOST', 'Pentecost'), ('NA', 'NA')], max_length=15, unique=True)),
                ('about', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
