# Generated by Django 2.0.1 on 2018-02-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
        ('song_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midi',
            name='likes',
            field=models.ManyToManyField(related_name='midi_likes', to='siteuser.SiteUser'),
        ),
    ]
