# Generated by Django 2.0.5 on 2018-06-09 08:04

from django.db import migrations, models
import song_media.utils


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='media_file',
            field=models.FileField(default=1, upload_to=song_media.utils.save_score),
            preserve_default=False,
        ),
    ]
