# Generated by Django 2.0.5 on 2018-06-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midi',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='song_media.VocalPart'),
        ),
        migrations.AlterField(
            model_name='score',
            name='notation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='song_media.ScoreNotation'),
        ),
        migrations.AlterField(
            model_name='score',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='song_media.VocalPart'),
        ),
        migrations.AlterField(
            model_name='score',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='song.Song'),
        ),
    ]
