# Generated by Django 2.0.1 on 2018-02-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midi',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
