# Generated by Django 2.0.5 on 2018-05-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midi',
            name='fsize',
            field=models.FloatField(null=True),
        ),
    ]
