# Generated by Django 2.0.1 on 2018-03-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midi',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
