# Generated by Django 2.0.1 on 2018-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
