# Generated by Django 2.0.5 on 2018-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0002_auto_20180523_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='fsize',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midi',
            name='fsize',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
