# Generated by Django 2.0.1 on 2018-03-24 17:20

from django.db import migrations, models
import sorl.thumbnail.fields
import universal.media_handlers


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0002_auto_20180320_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='playlist',
            field=models.CharField(default='playlist', max_length=100),
        ),
        migrations.AddField(
            model_name='videolink',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=universal.media_handlers.save_video_thumbnail),
        ),
        migrations.AddField(
            model_name='videolink',
            name='title',
            field=models.CharField(default='video title', max_length=100),
        ),
    ]
