# Generated by Django 2.0.1 on 2018-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0002_auto_20180425_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='drive_url',
            field=models.URLField(default='http://www.choralcentral.net'),
        ),
    ]
