# Generated by Django 2.0.1 on 2018-02-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0002_midi_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midi',
            name='part',
        ),
        migrations.AddField(
            model_name='midi',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='song_media.VocalPart'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='score',
            name='notation',
        ),
        migrations.AddField(
            model_name='score',
            name='notation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='song_media.ScoreNotation'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='score',
            name='part',
        ),
        migrations.AddField(
            model_name='score',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='song_media.VocalPart'),
            preserve_default=False,
        ),
    ]
