# Generated by Django 2.0.5 on 2018-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0002_auto_20180609_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='midi',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
