# Generated by Django 2.0.1 on 2018-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0003_auto_20180324_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='video_playlist_link',
            field=models.CharField(default='playlist link', max_length=100),
        ),
    ]
