# Generated by Django 2.0.5 on 2018-05-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0003_auto_20180523_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midi',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='score',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='score',
            name='views',
        ),
    ]
