# Generated by Django 2.0.1 on 2018-02-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0003_auto_20180206_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midi',
            old_name='file',
            new_name='media_file',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='file',
            new_name='media_file',
        ),
    ]
