# Generated by Django 2.0.1 on 2018-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0003_score_drive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='midi',
            name='drive_url',
            field=models.URLField(default='http://www.choralcentral.net'),
        ),
    ]
