# Generated by Django 2.0.5 on 2018-06-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0003_auto_20180614_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midi',
            options={'ordering': ('-like_count', '-downloads', 'created')},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-like_count', '-downloads', 'created')},
        ),
        migrations.AlterField(
            model_name='midi',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='siteuser.SiteUser'),
        ),
        migrations.AlterField(
            model_name='score',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='siteuser.SiteUser'),
        ),
        migrations.AlterField(
            model_name='videolink',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='siteuser.SiteUser'),
        ),
    ]
