# Generated by Django 2.0.1 on 2018-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0004_videolink_video_playlist_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='thumbnail_url',
            field=models.URLField(default='www.youtube.com'),
        ),
    ]
