# Generated by Django 2.0.5 on 2018-05-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0004_auto_20180523_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midi',
            name='drive_download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midi',
            name='drive_view_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midi',
            name='embed_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='drive_download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='drive_view_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='embed_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
