# Generated by Django 2.0.1 on 2018-02-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0005_auto_20180206_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorenotation',
            name='name',
            field=models.CharField(default='Solfa', max_length=30, unique=True),
        ),
    ]
