# Generated by Django 2.0.1 on 2018-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0005_videolink_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='channel_link',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='videolink',
            name='video_link',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
