# Generated by Django 2.0.1 on 2018-04-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0005_auto_20180429_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midi',
            old_name='drive_url',
            new_name='drive_view_link',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='drive_url',
            new_name='drive_view_link',
        ),
    ]
