# Generated by Django 2.0.5 on 2018-05-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0006_auto_20180524_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midi',
            name='embed_link',
        ),
    ]
