# Generated by Django 2.0.1 on 2018-04-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0006_auto_20180429_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='midi',
            name='drive_download_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='drive_download_link',
            field=models.URLField(null=True),
        ),
    ]
