# Generated by Django 2.0.1 on 2018-05-01 07:48

from django.db import migrations, models
import universal.media_handlers


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0008_score_pdf_embed_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='midi',
            name='fformat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='midi',
            name='media_file',
            field=models.FileField(null=True, upload_to=universal.media_handlers.save_midi),
        ),
        migrations.AlterField(
            model_name='score',
            name='media_file',
            field=models.FileField(null=True, upload_to=universal.media_handlers.save_score),
        ),
    ]
