# Generated by Django 2.0.1 on 2018-05-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_media', '0010_midi_embed_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='embed_link',
            new_name='embed_link',
        ),
    ]
