# Generated by Django 2.0.1 on 2018-01-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created', 'status']},
        ),
    ]
