# Generated by Django 2.0.1 on 2018-03-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('request',)},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('status', '-created')},
        ),
        migrations.AddField(
            model_name='request',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='song.Song'),
        ),
    ]
