# Generated by Django 2.0.1 on 2018-01-14 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20180114_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='originator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteuser.SiteUser'),
        ),
    ]
