# Generated by Django 2.0.1 on 2018-02-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20180206_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
