# Generated by Django 2.0.5 on 2018-06-12 23:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import siteuser.utils
import universal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to=siteuser.utils.badge_icon)),
                ('hierarchy', models.IntegerField()),
                ('siteuser', models.ManyToManyField(to='siteuser.SiteUser')),
            ],
            options={
                'ordering': ('hierarchy',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('body', models.CharField(max_length=200)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipient', to='siteuser.SiteUser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteuser.SiteUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
