# Generated by Django 2.0.5 on 2018-06-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'ordering': ('created', 'screen_name'), 'verbose_name_plural': 'siteusers'},
        ),
    ]
