# Generated by Django 2.0.1 on 2018-05-05 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import universal.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('quota', models.IntegerField(default=100)),
                ('siteuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteuser.SiteUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
