# Generated by Django 2.0.5 on 2018-06-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0002_badge_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
