# Generated by Django 2.0.5 on 2018-06-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0003_message_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('read', '-created')},
        ),
        migrations.AddField(
            model_name='message',
            name='inbox',
            field=models.BooleanField(default=False),
        ),
    ]
