# Generated by Django 2.0.1 on 2018-05-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0004_auto_20180507_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='remaining',
            new_name='used',
        ),
    ]
