# Generated by Django 2.0.5 on 2018-06-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0004_auto_20180615_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='inbox',
        ),
        migrations.AddField(
            model_name='message',
            name='outbox',
            field=models.BooleanField(default=True),
        ),
    ]
