# Generated by Django 2.1.5 on 2019-01-22 22:59

from django.db import migrations, models
import django.utils.timezone
import universal.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0004_auto_20180707_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='key',
        ),
    ]
