# Generated by Django 2.0.5 on 2018-06-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0005_auto_20180615_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='outbox',
        ),
    ]
