# Generated by Django 2.0.5 on 2018-05-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0005_auto_20180507_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
    ]
