# Generated by Django 2.0.5 on 2018-06-15 10:52

from django.db import migrations, models
import django.utils.timezone
import universal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0006_remove_message_outbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('code_name', models.CharField(max_length=50)),
                ('siteuser', models.ManyToManyField(to='siteuser.SiteUser')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
