# Generated by Django 2.0.5 on 2018-06-16 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0007_siteuserpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_id',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
