# Generated by Django 2.0.5 on 2018-06-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0009_auto_20180617_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon',
        ),
    ]
