# Generated by Django 2.0.5 on 2018-06-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0010_remove_badge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='color',
            field=models.CharField(default='silver', max_length=30),
            preserve_default=False,
        ),
    ]
