# Generated by Django 2.0.5 on 2018-06-17 17:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0011_badge_color'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siteuser',
            managers=[
                ('reverse_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
