# Generated by Django 2.0.5 on 2018-06-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0012_auto_20180617_2112'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siteuser',
            managers=[
            ],
        ),
    ]
